apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
data:
  load_test: |
    #!/bin/bash
    # Script to to invoke JMeter test script with the slave pod IP addresses
    # Example: ./load_test jmeter-test-script.jmx
    /jmeter/apache-jmeter-*/bin/jmeter -n -t $1 -Dserver.rmi.ssl.disable=true -R `getent ahostsv4 jmeter-slaves-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`
---
apiVersion: apps/v1beta2 # For Kube versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmmaster
        image: quay.io/alanpep/jmeter511-master:latest
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: loadtest
            mountPath: /load_test
            subPath: "load_test"
        ports:
        - containerPort: 60000
      volumes:
      - name: loadtest
        configMap:
         name: jmeter-load-test